### PR TITLE
Review needed: Make rules into an array of rule object

### PR DESCRIPTION
**Pull request by alistair3149**
This is still a work in progress, need some general and code style feedback.

Making rules into proper objects will allow us to: 
- Add other properties to each rules (see below)
- More readable and easier to maintain
- Easier to implement i18n later

For example, it will be helpful to have:
- Description: So that we can provide more insight into the issue and how to solve it
- Severity: So that we can triage issues into different categories, as the issues does not have the same importance

Current draft:
```js
{
    title: 'Skin does not show the article',
    description: '',
    condition: $( '.mw-body-content' ).length > 0
}
```
Questions:
- Should rules definition and score be in separate files?
- What else should go into the rule object?

### CODE REVIEW

**Comment by alistair3149** [comment]
@jdlrobson Sorry for the ping, what do you think about this?

**Comment by jdlrobson** [comment]
I think this is much clearer!

I trust your judgment on whether the rules should be in separate files, but I think title, condition and description is a good phase one!

Generally: As a skin developer, you probably have a better idea of what would be useful to you and others!

**Comment by jdlrobson** [comment]
I'd be happy to merge this as is, but will need to pull it down and test first. Have added to my todo list!

**Comment by alistair3149** [comment]
> I think this is much clearer!
> 
> I trust your judgment on whether the rules should be in separate files, but I think title, condition and description is a good phase one!
> 
> Generally: As a skin developer, you probably have a better idea of what would be useful to you and others!

I'm not sure what is the best practice to do it cleaner in a separate file, coding is unfortunately not my strong suit.

As for usefulness, I believe that communicating actionable feedbacks for each failed test would be the next step, but this is the prerequisite for adding more information to each rules.

**Review by jdlrobson — APPROVED** [review]
This is much cleaner! Thank you!

**Comment by jdlrobson** [comment]
This is great! Sorry for the delay on review for this one. It's been a crazy week! :D

**Comment by alistair3149** [comment]
No worries. Thank you so much for merging the PR!

**Pull request merged**
